'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    const words = [
      'abacaxi',
      'abelha',
      'anel',
      'aranha',
      'árvore',
      'cabelo',
      'cachorro',
      'cama',
      'caminhão',
      'carro',
      'casa',
      'celular',
      'chapéu',
      'chave',
      'chiclete',
      'chuva',
      'cobra',
      'colher',
      'copo',
      'criança',
      'cruz',
      'dedo',
      'dente',
      'dente',
      'dragão',
      'escova',
      'estrela',
      'explosão',
      'faca',
      'flecha',
      'flor',
      'fogão',
      'formiga',
      'fralda',
      'galinha',
      'gato',
      'girafa',
      'igreja',
      'jacaré',
      'janela',
      'laranja',
      'livro',
      'lápis',
      'língua',
      'macaco',
      'maçã',
      'mesa',
      'microfone',
      'morango',
      'mosca',
      'mão',
      'nariz',
      'nuvem',
      'olha',
      'ovo',
      'panela',
      'pato',
      'pedra',
      'peixe',
      'placa',
      'planta',
      'prato',
      'pé',
      'rato',
      'refrigerante',
      'relógio',
      'sapato',
      'sapo',
      'sofá',
      'sol',
      'soprar',
      'tapete',
      'tenis',
      'tesoura',
      'tigre',
      'travesseiro',
      'trem',
      'trigre',
      'umbigo',
      'unha',
      'uva',
      'vaca',
      'vassoura',
      'zebra',
      'zero',
    ]

    const silables = [
      ['a', 'ba', 'ca', 'xi'],
      ['a', 'be', 'lha'],
      ['a', 'nel'],
      ['a', 'ra', 'nha'],
      ['ár', 'vo', 're'],
      ['ca', 'be', 'lo'],
      ['ca', 'chor', 'ro'],
      ['ca', 'ma'],
      ['ca', 'mi', 'nhão'],
      ['car', 'ro'],
      ['ca', 'sa'],
      ['ce', 'lu', 'lar'],
      ['cha', 'péu'],
      ['cha', 've'],
      ['chi', 'cle', 'te'],
      ['chu', 'va'],
      ['co', 'bra'],
      ['co', 'lher'],
      ['co', 'po'],
      ['cri', 'an', 'ça'],
      ['cruz'],
      ['de', 'do'],
      ['den', 'te'],
      ['den', 'te'],
      ['dra', 'gão'],
      ['es', 'co', 'va'],
      ['es', 'tre', 'la'],
      ['ex', 'plo', 'são'],
      ['fa', 'ca'],
      ['fle', 'cha'],
      ['flor'],
      ['fo', 'gão'],
      ['for', 'mi', 'ga'],
      ['fral', 'da'],
      ['ga', 'li', 'nha'],
      ['ga', 'to'],
      ['gi', 'ra', 'fa'],
      ['i', 'gre', 'ja'],
      ['ja', 'ca', 'ré'],
      ['ja', 'ne', 'la'],
      ['la', 'ran', 'ja'],
      ['li', 'vro'],
      ['lá', 'pis'],
      ['lín', 'gua'],
      ['ma', 'ca', 'co'],
      ['ma', 'çã'],
      ['me', 'sa'],
      ['mi', 'cro', 'fo', 'ne'],
      ['mo', 'ran', 'go'],
      ['mos', 'ca'],
      ['mão'],
      ['na', 'riz'],
      ['nu', 'vem'],
      ['o', 'lha'],
      ['o', 'vo'],
      ['pa', 'ne', 'la'],
      ['pa', 'to'],
      ['pe', 'dra'],
      ['pei', 'xe'],
      ['pla', 'ca'],
      ['plan', 'ta'],
      ['pra', 'to'],
      ['pé'],
      ['ra', 'to'],
      ['re', 'fri', 'ge', 'ran', 'te'],
      ['re', 'ló', 'gio'],
      ['sa', 'pa', 'to'],
      ['sa', 'po'],
      ['so', 'fá'],
      ['sol'],
      ['so', 'prar'],
      ['ta', 'pe', 'te'],
      ['te', 'nis'],
      ['te', 'sou', 'ra'],
      ['ti', 'gre'],
      ['tra', 'ves', 'sei', 'ro'],
      ['trem'],
      ['tri', 'gre'],
      ['um', 'bi', 'go'],
      ['u', 'nha'],
      ['u', 'va'],
      ['va', 'ca'],
      ['vas', 'sou', 'ra'],
      ['ze', 'bra'],
      ['ze', 'ro']
    ]

    for (const [index, value] of words.entries()) {
      await queryInterface.bulkInsert('Words', [{
        description: value,
        silables: JSON.stringify(silables[index]),
        filename: `/assets/images/words/${value}.png`
      }], {})
    }
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     */
    await queryInterface.bulkDelete('Words', null, {});
  }
};
